[build-system]
requires = ["maturin>=1.5"]
build-backend = "maturin"

[project]
name = "lipilekhika"
version = "0.0.0a1"
description = "Lipi Lekhika is a library for transliterating text from one script to another."
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
dependencies = []

[tool.maturin]
bindings = "pyo3"
module-name = "lipilekhika._lipilekhika"
manifest-path = "binding/Cargo.toml"
python-source = "."

[dependency-groups]
dev = [
    "typer>=0.21.1",
]
