[workspace]
members = [
    "desktop-client",
    "packages/rust",
    "desktop-client/lipiparivartaka/src-tauri",
    "packages/js/wasm",
    "packages/python/binding",
    "packages/dart/binding",
    "plugins/fcitx5/binding",
]
resolver = "3"
