[package]
name = "lipilekhika-wasm"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
lipilekhika = { path = "../../rust" }
wasm-bindgen = "0.2"
js-sys = "0.3"
