[package]
name = "lipilekhika"
license = "MIT"
description = "A transliteration library for Indian Brahmic scripts"
homepage = "https://lipilekhika.in"
repository = "https://github.com/shubhattin/lipilekhika"
documentation = "https://lipilekhika.in/getting-started/rust"
keywords = ["indic-scripts", "transliteration"]
categories = ["text-processing", "localization"]

version = "1.0.5"
edition = "2024"
include = ["src/**/*", "build.rs", "Cargo.toml", "LICENSE*", "README*"]


[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
clap = { version = "4.5.54", features = ["derive"] }
indexmap = { version = "2", features = ["serde"] }

[dev-dependencies]
owo-colors = "4.2.0"
serde_yaml_ng = "0.10.0"
criterion = { version = "0.5.1", default-features = true }

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.148"
bincode = "1.3.3"
indexmap = { version = "2", features = ["serde"] }

[lib]
crate-type = ["rlib"]

[[bin]]
name = "parivartak"
path = "src/bin/parivartak.rs"

[[bench]]
name = "benchmark"
path = "src/benches/benchmark.rs"
harness = false
