[package]
name = "lipilekhika"
license = "MIT"
description = "A transliteration library for Indian Brahmic scripts"
homepage="https://lipilekhika.in"
repository = "https://github.com/shubhattin/lipilekhika"
documentation = "https://lipilekhika.in/getting-started/rust"
keywords = ["indic-scripts", "transliteration"]
categories = ["encoding", "text-processing"]


version = "0.0.1-beta.3"
edition = "2024"

[dependencies]
rust-embed = "8.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.148"

[dev-dependencies]
owo-colors = "4.2.0"
serde_yaml_ng= "0.10.0"
criterion = { version = "0.5.1", default-features = true }

[lib]
crate-type = ["rlib"]

[[bench]]
name = "benchmark"
path = "src/benches/benchmark.rs"
harness = false

include = [
    "src/**/*",
    "Cargo.toml",
    "LICENSE*",
    "README*"
]