[package]
name = "lipilekhika"
version = "0.0.0-alpha.1"
edition = "2024"

[dependencies]
rust-embed = "8.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.148"

[dev-dependencies]
owo-colors = "4.2.0"
serde_yaml_ng= "0.10.0"
criterion = { version = "0.5.1", default-features = true }

[lib]
crate-type = ["rlib"]

[[bench]]
name = "benchmark"
path = "src/benches/benchmark.rs"
harness = false
