[package]
name = "lipilekhika-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
lipilekhika = { path = "../packages/rust" }
once_cell = "1.18"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_Globalization",
] }
